export const ar = {
  remember_me: "تذكرني",
  dont_have_account: "إذا لم يكن لديك حساب",
  register_now: "سجل الآن",
  account: "حساب",
  signin: "تسجيل الدخول",
  forgot_password: "نسيت كلمة المرور",
  forgot_password_1: "الرجاء إدخال رقم هاتفك المحمول و",
  secret_code: "الرمز السري",
  forgot_password_2: "سيتم إرساله إلى رقم هاتفك المحمول",
  send_code: "إرسال الرمز",
  or_sign_in: "أو تسجيل الدخول",
  verification: "التحقق",
  sent_to: "تم إرساله إلى",
  please_enter: "يرجى إدخال",
  confirm: "تأكيد",
  next: "التالي",
  name: "الاسم",
  register: "تسجيل",
  service_provider: "مزود الخدمة",
  customer: "العميل",
  company: "الشركة",
  terms: "أوافق على الشروط والأحكام",

  company_id: "معرف الشركة",
  location: "الموقع",
  municipality: "البلدية",
  country: "البلد",
  state: "الولاية",
  city: "المدينة",
  website: "الموقع الإلكتروني",
  company_license: "ترخيص الشركة",
  instagram_account: "حساب انستجرام",
  facebook_account: "حساب فيسبوك",
  our_work: "أعمالنا",
  create_account: "إنشاء حساب",

  home: "الرئيسية",
  request_services: "طلب الخدمات",
  services: "الخدمات",
  contact: "اتصل بنا",
  search: "البحث",
  form_subscribe: "الاشتراك في النشرة الإخبارية",
  join: "انضم",
  get_Professional: "الحصول على محترف",
  home_services: "خدمات المنزل",
  book_now: "احجز الآن",

  top_services: "أهم الخدمات",
  kitchen: "المطبخ",
  decoration: "الديكور",
  electricity: "الكهرباء",
  electrical: "الأجهزة الكهربائية",
  plumbing: "السباكة",
  carpentry: "النجارة",
  furniture: "الأثاث",
  paint: "الدهانات والجص",
  browse_services: "تصفح الخدمات",

  why_choose_us: "لماذا تختارنا؟",
  warranty_maintenance: "الضمان والصيانة",
  affordable_price: "أسعار معقولة",
  services24: "خدمات على مدار الساعة",
  latest_projects: "آخر مشروع لدينا",
  electricity: "الكهرباء",
  electricity_description: "فني الصيانة الخارجية لأجهزة التكييف",
  plumbing: "السباكة",
  plumbing_description: "خدمة التنظيف. إسفنج",

  client_say: "ماذا يقول عملاؤنا؟",
  discover_appointment: "استكشف واحجز العديد من الخدمات",
  our_team: "فريقنا الرائع",

  refrigerators: "الثلاجات",
  ovens: "الأفران",
  conditioners: "أجهزة التكييف",
  microwaves: "أجهزة الميكروويف",
  gas: "الغاز",
  others: "آخرون",

  service_providers: "مقدمو الخدمات بالقرب منك",
  view_profile: "عرض الملف الشخصي",
  see_more: "شاهد المزيد",
  see_all: "شاهد الكل",
  companies: "الشركات",
  about: "عن",
  some_work: "بعض أعمالي",
  customer_feedback: "آراء العملاء والتعليقات",
  get_in_touch: "تواصل معنا",
  subject: "الموضوع",
  message: "الرسالة",
  submit_now: "إرسال الآن",
  your_email: "بريدك الإلكتروني",
  email: "البريد الإلكتروني",

  request_services: "طلب الخدمات",
  enter_information: "أدخل المعلومات",
  confirmation: "تأكيد",
  wait_offers: "انتظر العروض",

  add_information: "إضافة معلومات",
  service_name: "اسم الخدمة",
  service_name_placeholder: "أعط وصفًا دقيقًا لمشكلتك",
  select_category: "اختر الفئة",
  select_time: "اختر الوقت",
  select_time_placeholder: "أضف الوقت الذي يعمل بالنسبة لك",
  select_date: "اختر التاريخ",
  select_date_placeholder: "أضف التاريخ الذي يعمل بالنسبة لك",
  add_details: "إضافة تفاصيل",
  description: "الوصف",
  description_placeholder: "أدخل وصفًا كاملاً",
  add_picture: "إضافة صورة للمشكلة",
  camera_capture: "التقاط الصورة",
  payment_method: "طريقة الدفع",

  credit_card_number: "رقم البطاقة الائتمانية",
  expiration_date: "تاريخ انتهاء الصلاحية",

  service_provider: "مقدم الخدمة",
  new_orders: "طلبات جديدة",
  my_offers: "عروضي",
  in_progress: "قيد التنفيذ",

  thank_you: "شكرا لك",
  soon: "سنتواصل معك بأقرب وقت ممكن",
  back_home: "العودة الي الصفحة الرئيسية",

  submit_offer: "إرسال العرض",
  view_details: "عرض التفاصيل",

  final_price: "أدخل السعر النهائي الخاص بـ",
  expected_time: "أدخل الوقت المتوقع للوصول",
  how_long_service: "مدة الخدمة",
  enter_photo: "أضف صورًا لأعمالك السابقة",
  offer_details_label: "أدخل تفاصيل العرض الخاص بك",
  more_offers: "عرض المزيد من العروض",
  send: "إرسال",
  done: "مكتمل",
  cancel: "إلغاء",
  confirm: "تأكيد",
  edit_offer: "تعديل العرض",
  offer_update_message: "تم تحديث العرض بنجاح",

  reason_label: "ما هو السبب في إلغاء الطلب؟",
  enter_here: "أدخل هنا",
  job_done_msg: "هل أنت متأكد من أن العمل تم إنجازه؟",
  add_feedback: "إضافة تعليق",
  add_comment: "إضافة تعليق",

  reviews: "التقييمات",
  earning: "الأرباح",

  hr: "ساعة",
  profile_information: "المعلومات الشخصية",
  phone_number: "رقم الهاتف",
  phone: "الهاتف",
  email: "البريد الالكتروني",
  address: "العنوان",
  user_name: "اسم المستخدم",
  payments: "المدفوعات",
  settings: "الإعدادات",
  packages: "الباقات",
  companies_and_suggestions: "الشكاوى والاقتراحات",
  logout: "تسجيل الخروج",
  password: "كلمة المرور",
  add_payment: "إضافة وسيلة دفع جديدة",
  month: "شهر",
  add: "إضافة",
  choose_plan: "اختر أفضل خطة لك",
  login: "تسجيل الدخول",
  signup: "أشتراك",
  languages: "اللغات",
  privacy_policy: "سياسة الخصوصية",
  term_use: "شروط الاستخدام",
  support: "الدعم",
  How_help_you: "كيف يمكننا مساعدتك؟",
  problem_here: "أدخل المشكلة هنا",
  email_us: "راسلنا",
  contact_us: "اتصل بنا",
  ads_msg: "تم إرسال اقتراحاتك وسيتم الرد عليها في أقرب وقت ممكن",
  title: "العنوان",
  message_placeholder: "اكتب",
  languages: "اللغات",
  privacy_policy: "سياسة الخصوصية",
  term_use: "شروط الاستخدام",
  support: "الدعم الفني",
  How_help_you: "كيف يمكننا مساعدتك؟",
  problem_here: "أدخل المشكلة هنا",
  email_us: "راسلنا عبر البريد الإلكتروني",
  contact_us: "تواصل معنا",
  ads_msg: "تم إرسال مقترحاتك وسيتم الرد عليها في أقرب وقت ممكن",
  title: "العنوان",
  message_placeholder: "اكتب رسالتك هنا",
  optional: "اختياري",
  upload_photo: "رفع صورة",
  photo: "الصور",
  confirm_send: "تأكيد و أرسال",
  profile: "حسابي",
  my_requests: "طلباتي",
  offers: "عروضي",
  notification: "الاشعارات",
  now: "الان",
  orders: "الطلبات",
  current_orders: "الطلبات الحالية",
  previous_orders: "الطلبات السابقة",
  canceled_orders: "الطلبات الملغية",
  all_offers: "جميع العروض",
  view_offers: "شاهد العروض",
  accept_offer: "قبول العرض",
  basic: "الباقة البسيطة",
  standard: "الباقة القياسية",
  premium: "الباقة المميزة",
  our_client: "عملائنا",
  my_works: "أعمالي",

  optional: "اختياري ",
  upload_photo: "تحميل صورة",
  payment_available: "وسائل الدفع المتاحة",
  follow_us: "تابعنا",
  waiting_confirm: "بانتظار التاكيد",
  waiting_approval: "بانتظار الموافقة",
  register: "تسجيل",
  confirm_password: "تاكيد كلمة السر",
  company_name: "اسم الشركة",
  accept_the_offer: "قبول العرض",
  add_offer_message: "تم اضافة الطلب بنجاح و جاري معالجته",
  save: "حفظ",
};
export const getWordAr = (key) => {
  return ar[key];
};
