export const en = {
  expressDelivery: "Express Deilivery and free returns within 30 days",
  downloadApp: "download app",
  locatePoints: "locate J&T points",
  trackParcel: "track your parcel",
  merchantLogin: "merchant login",
  home: "home",
  aboutUs: "About us",
  pudoSignup: "pudo sign up",
  blog: "blog",
  contactUs: "contact us",
  support: "support",
  email: "E-main",
  home1Title: "SEAMLESS INTEGRATION WITH OUR E-COMMERCE PARTNERS",
  home1Descriptions: [
    "Whether you’ve set up shop on Shopify, Shopcada, WooCommerce, or anywhere else, we make it incredibly easy for you to ship your parcels through our strong integrations with leading platforms. We’re also an official courier delivery partner of major marketplaces such as Lazada and Shopee.",
  ],
  home2Title: "HASSLE-FREE RETURN AND EXCHANGE",
  home2Descriptions: [
    "Mistakes happen. Make the return process as effortless as possible for you and your customers.",
    "bulletpoint-Red-Tick We’re one of the few third party logistics providers(3PL) that offers return service",
    "bulletpoint-Red-Tick Complimentary Door-to-door pick-up and delivery",
    "bulletpoint-Red-Tick Paperless pick-up—your buyers can just hand over the parcel to our drivers, who have a portable printer to print out the waybill on the spot!",
    "bulletpoint-Red-Tick The most competitive pricing in the market—starts at $3.50",
  ],
  home3Title: "COMPETITIVE RATES FOR PARCELS BIG AND SMALL",
  home3Descriptions: [
    " Ship parcels up to 60kg for domestic last mile deliveries",
    "bulletpoint-Red-Tick Enjoy a 0-1kg weight break to deliver smaller items - such as electronic gadgets, toys and miniatures, fashion and apparel affordably",
  ],
  home4Title: "PICK-UP AND DROP-OFF AT YOUR OWN PACE",
  home4Descriptions: [
    "Schedule pick-ups after working hours (6:00P.M.-9:00 P.M.), or drop your parcels off at the nearest sealal Point during working hours. Better yet, have your items collected the same day from 400+  sealal Points islandwide.",
    "Shopee sellers can now also drop packages off at any  sealal Point. Click here to find out more.",
  ],
  home5Title: "FULFILMENT & WAREHOUSING SOLUTIONS",
  home5Descriptions: [
    "Scale your business with the help of our one-stop integrated eCommerce solutions and a dedicated fulfilment warehouse in Singapore - we have enough space for all your awesome products.",
  ],
  home6Title: "BONUS! YOUR OWN SALES SUPPORT TEAM IS JUST A CHAT AWAY",
  home6Descriptions: [
    "We take customer care seriously. That’s why our busiest clients get a direct line of communication with a dedicated sales support team.",
  ],
  shipping: "Shipping",
  internalShipping: "internal shipping",
  internationalShipping: "international shipping",
  internalShippingDescription:
    "Schedule pick-ups after working hours (6:00P.M.-9:00 P.M.), or drop your parcels off at the nearest sealal Point during working hours. Better yet, have your items collected the same day from 400+  sealal Points islandwide.",
  internationalShippingDescription:
    "Schedule pick-ups after working hours (6:00P.M.-9:00 P.M.), or drop your parcels off at the nearest sealal Point during working hours. Better yet, have your items collected the same day from 400+  sealal Points islandwide.",
  whyUs: "why US?",
  effortless: "effortless",
  efficient: "efficient",
  seamless: "seamless",
  keenTo: "Keen to know more?",
  contactUs: "Contact us",
  contactUsDescription: "Contact us 24 hours a say, 7 days a week",
  whatClientsSay: "what our clients say",
  whatClientsSayDescription:
    "Hear from our client, BooksActually. Find out more and read the full Case Study",
  here: "here",
  copyRight: "Copyright © 2022 sealal Inc. All rights reserved.",
  aboutUsDescription:
    "Orci varius nato que penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer vel nisi lorem. Donec dignissim non est ut pulvinar. Dlobortis metus libero commodo rhon cusnunc libero tarcu.",
  usefulLinks: "useful links",
  helpSupport: "help $ support",
  getInTouch: "Get in touch",
  agencies: "agencies",
  contact: "contact",
  login: "login",
  myAccount: "my account",
  subscribe: "subscribe",
  contact: "contact",
  fastShipping: "Fast shipping",
  lastMile: "last mile delivery",
  doorToDoor:
    "Door-to-Door Singapore Courier Service Safely, Reliably, Conveniently",
  deliveryPartner: "Top SINGAPORE ECOMMERCE DELIVERY PARTNER",
  // home page
  shippingRates: "Find out about shipping rates",
  // footer subscribe
  yourEmail: "Your email",
  // join page
  joinOurPudo: "JOIN OUR PUDO NETWORK",
  bePartOfPudo:
    "Be part of our growing network of PUDO points and reap from the benefits!",
  submit: "submit",
  whatIsPudo: "WHAT IS A PUDO POINT?",
  step1: "step 1",
  orderPlaced: "order placed",
  pudoPoints1:
    "Consumer purchased an item online through Shopee, Lazada, Zalora or others.",
  step2: "step 2",
  orderDelivered: "order delivered",
  pudoPoints2:
    "Consumer purchased an item online through Shopee, Lazada, Zalora or others.",
  step3: "step 3",
  parcelCollected: "parcel collected",
  pudoPoints3:
    "Consumer purchased an item online through Shopee, Lazada, Zalora or others.",
  step4: "step 4",
  commissionRewarded: "commission rewarded",
  pudoPoints4:
    "Consumer purchased an item online through Shopee, Lazada, Zalora or others.",
  pudoBenefits: "BENEFITS OF Sealal PUDO DROP POINT",
  additionalTraffic: "ADDITIONAL FOOT TRAFFIC",
  pudoBenefits1:
    "Enjoy increased customer traffic to your store when you allow J&T drop off. eCommerce is booming, expect new and returning patrons to your store.",
  additionalRevenue: "ADDITIONAL REVENUE STREAM",
  pudoBenefits2:
    "Enjoy increased customer traffic to your store when you allow J&T drop off. eCommerce is booming, expect new and returning patrons to your store.",
  storePudo: "CAN MY STORE BE A PUDO POINT?",
  pudoRequirements: "WHAT ARE THE REQUIREMENTS?",
  pudoRequirementsDescription: [
    "bulletpoint-Red-Tick Your shop can be located easily.",
    "bulletpoint-Red-Tick Your shop is open to include J&T Express branding.",
    "bulletpoint-Red-Tick You are willing to allocate space for J&T Express parcel drop-off.",
  ],

  login: "login",
  signup: "Signup",
  forgot_password: "Forget Password",
  forgot_password_1: "Please enter your mobile number and a",
  secret_code: "secret code",
  forgot_password_2: "will be sent to your mobile number",
  send_code: "send code",
  or_sign_in: "or Sign in",
  verification: "verification",
  sent_to: "sent to",
  please_enter: "Please enter the",
  confirm: "Confirm",
  next: "Next",
  name: "Name",
  register: "Register",
  service_provider: "service provider",
  customer: "customer",
  company: "company",
  terms: "I agree with Terms and Conditions",

  company_id: "company id",
  location: "Location",
  municipality: "Municipality",
  country: "Country",
  state: "State",
  city: "City",
  website: "Website",
  company_license: "Company License",
  instagram_account: "instagram account",
  facebook_account: "facebook account",
  our_work: "Our work",
  create_account: "create account",

  home: "Home",
  request_services: "request services",
  services: "Services",
  contact: "Contact",
  search: "Search",
  form_subscribe: "Subscribe to our newsletter",
  join: "Join",
  get_Professional: "Get Professional",
  home_services: "Home Services",
  book_now: "Book Now",

  top_services: "Top Services",
  kitchen: "Kitchen",
  decoration: "Decoration",
  electricity: "Electricity",
  electrical: "Electrical Devices",
  plumbing: "Plumbing",
  carpentry: "Carpentry",
  furniture: "Furniture",
  paint: "Paint & Gypsum",
  browse_services: "browse services",

  why_choose_us: "Why choose us ?",
  warranty_maintenance: "Warranty & Maintenance",
  affordable_price: "Affordable Price",
  services24: "24/7 Services",

  latest_projects: "Our Latest Project",
  electricity: "Electricity",
  electricity_description: "Technician utside AC",
  plumbing: "plumbing",
  plumbing_description: "Cleaning service. Sponges",

  client_say: "What Our Clients Say ?",
  discover_appointment: "Discover and appointment a lot of services",
  our_team: "Our Great Team",

  refrigerators: "refrigerators",
  ovens: "ovens",
  conditioners: "conditioners",
  microwaves: "microwaves",
  gas: "Gas",
  others: "Others",

  hr: "hr",

  service_providers: "Service Providers near you",
  view_profile: "view profile",
  see_more: "see more",
  companies: "companies",
  about: "about",
  some_work: "some of my work",
  customer_feedback: "Customer feedback and comment",
  get_in_touch: "Get in touch",
  subject: "Subject",
  message: "Message",
  submit_now: "Submit now",
  your_email: "your email",

  request_services: "Request Services",
  enter_information: "Enter information",
  confirmation: "Confirmation",
  wait_offers: "Wait offers",

  add_information: "Add Information",
  service_name: "Service Name",
  service_name_placeholder: "Give an accurate description of your problem",
  select_category: "Select Category",
  select_time: "Select Time",
  select_time_placeholder: "Add ime that works for you",
  select_date: "Select Date",
  select_date_placeholder: "Add a date hat works for you",
  add_details: "Add Details",
  description: "Description",
  description_placeholder: "Enter a full description",
  add_picture: "Add a picture of the problem",
  camera_capture: "Camera Capture",
  payment_method: "Payment Method",

  credit_card_number: "Credit card number",
  expiration_date: "Expiration date",
  cvv: "CVV",
  photo: "photos",
  confirm_send: "Confirm and Send",

  profile: "Profile",
  my_requests: "My Requests",
  offers: "Offers",
  notification: "Notification",

  current_orders: "Current Orders",
  previous_orders: "Previous Orders",
  canceled_orders: "Canceled Orders",

  view_offers: "View the offers",
  all_offers: "all offers",
  see_all: "see all",
  accept_offer: "Accept the offer",

  thank_you: "Thank You",
  soon: "We will contact you as soon as possible",
  back_home: "Back Home",
  service_provider: "service provider",
  new_orders: "new orders",
  my_offers: "my offers",
  in_progress: "in progress",

  submit_offer: "Submit Offer",
  view_details: "view details",

  final_price: "Enter your final price for the",
  expected_time: "Enter the expected time to go",
  how_long_service: "How long is the service ",
  enter_photo: "Enter photos of your previous work",
  offer_details_label: "Enter your offer details",
  more_offers: "view more offers",
  send: "Send",
  done: "Done",
  cancel: "Cancel",
  confirm: "Confirm",
  edit_offer: "edit offer",
  offer_update_message: "The offer has been successfully update",

  reason_label: "What is the reason for canceling the order?",
  enter_here: "Enter here",
  job_done_msg: "Are you sure you got the job done?",
  add_feedback: "Add Feedback",
  add_comment: "Add comment",

  reviews: "reviews",
  earning: "earning",

  profile_information: "Personal Information",
  phone_number: "Phone Number",
  phone: "Phone",
  email: "Email",
  address: "Address",
  user_name: "User name",
  payments: "Payments",
  settings: "Settings",
  packages: "Packages",
  companies_and_suggestions: "Complaints and suggestions",
  logout: "Logout",
  password: "Password",
  add_payment: "add new payment method",
  month: "month",
  add: "add",
  choose_plan: "Choose the best plan for you ",

  languages: "Languages",
  privacy_policy: "Privacy Policy",
  term_use: "Term of Use",
  support: "Support",
  How_help_you: "How can we help you ?",
  problem_here: "enter problem here",
  email_us: "email us",
  contact_us: "contact us",
  ads_msg:
    "Your suggestions have been sent and will e answered as soon as possible",
  title: "Title",
  message_placeholder: "Write your complaint message here",
  optional: "optional ",
  upload_photo: "Upload Photo",
  our_client: "our clients",
  my_works: "my works",
  payment_available: "Available payments",
  follow_us: "Follow us",
  waiting_confirm: "waiting confirm",
  waiting_approval: "waiting approval",
  register: "register",
  confirm_password: "confirm password",
  company_name: "company name",
  accept_the_offer: "accept the offer",
  add_offer_message: "The offer has been added and we will review it",
  save: "save",
  //
  //
  orders: "orders",
  basic: "basic",
  standard: "standard",
  premium: "premium",
};

export const getWordEn = (key) => {
  return en[key];
};
